# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_plugin "vagrant-chef-zero"
Vagrant.require_plugin "vagrant-berkshelf"

Vagrant.configure("2") do |config|
   config.vm.hostname = "playground"
   config.vm.box = "Ubuntu 12.04.2 server 64-bit VirtualBox basebox (VirtualBox 4.2.16 Guest Additions)"
   config.vm.box_url = "https://dl.dropboxusercontent.com/s/yfojlwxq66im9hk/misheska-ubuntu1204.box?token_hash=AAFUeOXWpPnRaPh6s_9JHKQiF0Y-q7rE8BrNxQN5d4Qj1Q&dl=1"
   config.omnibus.chef_version = :latest
   config.vm.network :private_network, ip: "33.33.33.10"
   config.ssh.max_tries = 40
   config.ssh.timeout   = 120
   config.berkshelf.enabled = true
   
   config.chef_zero.chef_repo_path = "playground/"
   #config.chef_zero.nodes = "playground/nodes"
   #config.chef_zero.environments = "playground/environments/baz.json"
   #config.chef_zero.data_bags = "playground/data_bags"
   #config.chef_zero.roles = "playground/roles/*.json"
   #config.chef_zero.cookbooks = "playground/cookbooks"
   
   config.vm.provision :chef_client do |chef|
    chef.json = {
      :mysql => {
        :server_root_password => 'rootpass',
        :server_debian_password => 'debpass',
        :server_repl_password => 'replpass'
      }
    }
    #chef.encrypted_data_bag_secret_key_path = '/etc/chef/encrypted_data_bag_secret'
    #chef.run_list = [
    #]
  end
end
